language: objective-c
cache:
  directories:
    - vendor/bundle
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - brew update
  - brew install carthage
  - carthage update --use-submodules
git:
  submodules: false
script:
  - bundle exec rake test:ios test:osx
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
