language: objective-c
osx_image: xcode8
script:
- set -o pipefail
- xcodebuild -scheme HMAC -sdk macosx build-for-testing test | xcpretty
- xcodebuild -scheme HMAC -sdk iphonesimulator -destination "name=iPhone 7" build-for-testing test | xcpretty
- xcodebuild -scheme HMAC -sdk appletvsimulator -destination "name=Apple TV 1080p" build-for-testing test | xcpretty
- xcodebuild -scheme HMAC -sdk watchsimulator -destination "name=Apple Watch - 38mm" build | xcpretty
- swift build && swift test
notifications:
  webhooks:
    secure: Axm4RNRydsHiB6Ak4c9Bf+rmhvTz6WMFphjPJKHdEUl3yt3M4C3g00v5a1M3ImW+NdEWFBIAnobE/pWbq7lT6nF2A+piSBjRozQCz13hjDq1HJ8MsFo1VX1vh1gagaajjs+1bibfBQD1DrX5bI1ZPWkM1o48RBCn6yTtcQBjE78=
